### ISSUE TITLE
UnHashPassword

### ISSUE THREAD

**Issue by avmp2208** [caevyn/PasswordHasher#6]
Hello friends, I know this a very old contribution but very strong and a good one, my question is, I there any way you can unhash the password stored? I notice there is not a valid method in this source to do that, I ask because I have to give a solution for help desk to unhash password so they give support the clients.

Best regards

**Comment by caevyn** [comment]
The point of a hash is that it should be non-reversable. You probably want to enable the user/service desk to reset the password. I.e. create a new password. Perhaps something like http://stackoverflow.com/questions/19524111/asp-net-identity-reset-password/23094238

**Comment by avmp2208** [comment]
Yes, I told them the same but is usless to deal with that, So I have to do it, because the problema is not to reset the password but login the client account to see his problem,

**Comment by caevyn** [comment]
If you want reversible, you need encryption, not hashing. It really isn't advisable. If you really need admin users to log in as users, you want to handle that differently. E.g. You could have admin accounts with more access, however, there are risks with that as well. If you are unsure you might want to engage a security consultant etc.
